cnctfacpBundle:
    resource: "@cnctfacpBundle/Resources/config/routing.yml"
    prefix:   /facp

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
